#!/usr/bin/env python
import os,sys,getopt,shutil
import lib_v2_ohlc as o

ndir = o.get_a_word()
update = False
try:
    with open('_session_name.txt') as f:
        ndir = f.readline().strip()
except:
    pass

argv = sys.argv[1:]
try:
    opts, args = getopt.getopt(argv, "-hu:d:", ["help","update=","dir="])
except getopt.GetoptError as err:
    sys.exit(2)

for opt, arg in opts:
    if opt in ("-h", "--help"):
        print("-h, --help   this info")
        print("-d, --dir  in ../RUNS")
        print("-u, --update <dir to update>")
        sys.exit(0)

    if opt in ("-d", "--dir"):
        ndir = arg

    if opt in ("-u", "--update"):
        update = True
        ndir = arg

fndir = f"../RUNS/{ndir}"
print(f"IN DIRECTIRY:: {fndir}")

if not update:
    print(f"deleting {fndir}")

    o.waitfor()
    os.system(f"rm -rf {fndir}")

    print(f"mkdir {fndir}")
    os.makedirs(fndir, exist_ok=True)

    shutil.copy("_session_name.txt",fndir)

os.system(f"./INS.sh {fndir}")

cmd = f'terminator -e > /dev/null 2>&1 "cd {fndir} && /bin/zsh"'
print(cmd)
print("------------------------------------------------------")
os.system(cmd)

